qlib_init:
    provider_uri: "E:\\qlib_data\\tushare_qlib_data\\qlib_bin"
    region: cn
market: &market all
benchmark: &benchmark 000300.sh
data_handler_config: &data_handler_config
    start_time: 2015-01-01
    end_time: 2025-11-01
    fit_start_time: 2015-01-01
    fit_end_time: 2025-10-28
    instruments: *market
    
port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal: <PRED>
            topk: 50
            n_drop: 5
            risk_degree: 1.0
    backtest:
        start_time: 2025-10-30
        end_time: 2025-11-01
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: 0.095
            deal_price: close
            open_cost: 0.0005
            close_cost: 0.0015
            min_cost: 5
task:
    experiment_name: "test_lgbm"
    model:
        class: LGBModel
        module_path: qlib.contrib.model.gbdt
        kwargs:
            loss: mse
            colsample_bytree: 0.6609785798727253
            learning_rate: 0.41407141856342733
            subsample: 0.1724475929360629
            lambda_l1: 1.300591783823068
            lambda_l2: 126.11558673433876
            num_leaves: 827
            feature_fraction: 0.8707909338344939
            bagging_fraction: 0.999947949742483
            bagging_freq: 2
            min_data_in_leaf: 3
            min_child_samples: 45
            max_depth: 10
    dataset:
        class: DatasetH
        module_path: qlib.data.dataset
        kwargs:
            handler:
                class: Alpha158
                module_path: qlib.contrib.data.handler
                kwargs: *data_handler_config
            segments:
                train: [2015-01-01, 2025-10-28]
                valid: [2025-10-28, 2025-10-30]
                test: [2025-10-30, 2025-11-01]
    record: 
        - class: SignalRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            model: <MODEL>
            dataset: <DATASET>
        - class: ShapRecord
          module_path: shap_record
          kwargs:
            model: <MODEL>
            dataset: <DATASET>
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            ana_long_short: False
            ann_scaler: 252
        - class: PortAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            config: *port_analysis_config
