type: "mysql"
database: "qlib"
database2: "portfolio_t1"
table_name: "data_score"
table_name2: "portfolio_weights"
chunk_size: 20000
workers: 4
user: "yfr"
password: "Abcd1234#"
host: "rm-cn-fhh4gzo9900083vo.rwlb.rds.aliyuncs.com"
port: 3306
